services:
  front:
    build: ./php
    image: teddyandria/cp-php
    ports:  
      - "8081:80"
    #volumes:
    #  - ./php/src:/var/www/html #permet de monter l'env src dans mon container pour un env de dev
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db # pour que ce container front fonctionne, il faut que db soit démarré. Db sera d'abord lancé ensuite il lancera front
  
  db:
    build: ./mysql
    image: teddyandria/cp-mysql:latest
    #ports: # pas nécessaire si on est en dev car on utilise le port 8080 du container front
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
    volumes:
      - mysql-cp-data:/var/lib/mysql #interessant de garder un volume pour retravailler dessus plus tard.

volumes:
    mysql-cp-data: